### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Amin-azimi93** [anfoss/PCprophet#13] opened 2022-01-03 22:08 UTC
**Describe the bug**
The PCprophet GUI does not generate any output files and runs nothing. Besides, it gives no error in the error log. Only says: 
=====Starting running PCprophet at 16:24:57.568039800=====
=====PCprophet has finished running at 16:24:57.951643600=====

**Extract of sample ids file and protein matrix used**
I used the default sample data files provided with the toolkit.

**To Reproduce**
I extracted the PCprophet_GUI_win.zip, copied the "PCprophet" folder (containing the .py files) into the PCprophet_GUI_win folder as mentioned in the user manual. I created the output folder manually in the PCprophet_GUI_win folder.

**Screenshots**
Attached are the screenshot of the GUI and the contents of the GUI folder
![PCprophet screenshot](https://user-images.githubusercontent.com/66635551/147985118-49d92300-66c1-4f65-addc-0cc76677ab9d.PNG)
![GUI folder content](https://user-images.githubusercontent.com/66635551/147985123-c9716bbb-e2b3-4b35-84b7-b59cbee3bb79.PNG)

**Desktop (please complete the following information):**
 - Windows 10 pro
 - Python 3

**Additional context**
Using the command line the toolkit works and it generates the output files as expected. However, I am not a skilled programmer, so I am trying to make the GUI work.
Choosing other files for the database makes no difference. Changing the sample ID directory into a wrong name (into a file.txt which does not exist) made no difference. From which I concluded that the run terminates before it gets to the point of reading the input file and database file.

**Comment by chenli-bioinfo** [comment] 2022-01-03 23:02
Thanks for your interest in using the GUI version of PCprophet. We tested the GUI version for both MacOS and Windows with the provided example test files before publishing it and it ran as expected. From the output, it seems that the program has an immediate error after hitting the run button. This immediate error can be caused by the failure of finding the right python command to run or relevant libraries. As this is a beta version, we have marked this error down and will keep working on it and update the GUI with new revisions. Thanks again for the report.

**Comment by chenli-bioinfo** [comment] 2022-01-04 07:47
Hi
I have tried the windows version and it ran as expected:
![3](https://user-images.githubusercontent.com/39520131/148025449-c606e2cd-5511-4393-8653-7b76dbad6812.png)

![4](https://user-images.githubusercontent.com/39520131/148025567-2c6f49bc-d0a3-46c4-9219-7d93cc4e0951.png)

To facilitate debugging, I have uploaded a revised version (GUI_debug/), where the error message will be shown in the console. For example, if I give the wrong name of Python command, it shows the following error message:

![1](https://user-images.githubusercontent.com/39520131/148025754-0a3cc7a5-babf-46f6-97cf-f5bb5fb2a428.png)
You can also try this with the original version of the Windows GUI. If you start GUI using the console, you will be able to see the error message if something is wrong. For example, regarding the error above, you can see the following message in the console:
![2](https://user-images.githubusercontent.com/39520131/148025922-235360ce-0ef7-4b05-a4cf-d0c8aa949757.png)
You can then have a try and let me know what the error message is if the problem still exists. Thanks.

**Comment by chenli-bioinfo** [comment] 2022-01-07 10:19
As there is no further communication, I am closing this thread. Please let us know if we can be any of assistance.

**Closed by chenli-bioinfo** 2022-01-07 10:19 UTC
Labels: bug
