### ISSUE TITLE
ICEsoft ICEpdf - Exception

### ISSUE THREAD

**Issue by Maithy15** [anfoss/PCprophet#12] opened 2021-11-29 15:17 UTC
Hi,

I am unable to visualize anything in PC prophet. It runs successfully but when I click visualize it gives me some error (please see the attached image).

Please let me know what I am doing wrong. 

Thanks

![image](https://user-images.githubusercontent.com/78071837/143893427-d87bbc3f-585e-47df-879f-01fc7fd3257d.png)

**Comment by anfoss** [comment] 2021-11-29 15:52
Can you attach one of the PDF which has this error?

I ran all the test successfully from my end.

Can you open them outside the GUI?

**Comment by chenli-bioinfo** [comment] 2021-11-29 20:59
Thank you for using our PCprophet!
The PDF issue may reflect unsuccessful processing of the running data, as redirecting the I/O error outputs from Python to Java can be problematic. I therefore suggest you check if the PDF file is empty. If the PDF file does exist but is empty, it means that your input data was not processed properly due to potential errors etc. This is often the reason you got the error message from ICEpdf. If you can't see any error messages from the GUI, you can run the command line version, which will output all possible error messages if something wrong happens. We can then investigate what the problem is. Thanks.

**Comment by Maithy15** [comment] 2021-11-30 08:57
Thanks to both of you for the reply! 

I do not get any output from the PCprophet itself. Could it be because of the Python version? The python version I have is 3.9.7.
I will try to do it in the command line and let you know.

Thanks

**Comment by chenli-bioinfo** [comment] 2021-11-30 09:59
Currently our GUI is a beta version. It involves a lot of Python docking to Java, in order to run PCprophet. Therefore there could be some glitches in the program, particularly in invoking Python and its packages. Simply let us know if you experience any problems running the command line version. Thanks.

**Comment by Maithy15** [comment] 2021-11-30 20:32
Hi,

The command-line version works. But, FDR estimation was not performed as not enough known complexes are found, and GO term mapping went wrong including some other warnings and errors. I have attached the text from the cmd for your reference.  will using the PPI database help in FDR estimation?

Thanks

[log.txt](https://github.com/anfoss/PCprophet/files/7628663/log.txt)

**Comment by anfoss** [comment] 2021-11-30 21:43
So a couple of questions.

1. what is your sklearn version? It seems it is not the recommended one.
2. How is your input file format? Can you post the first 3 or 4 files?

Thanks

**Comment by Maithy15** [comment] 2021-12-01 08:32
Hi

1. The first column is GN and the second is ID followed by fraction numbers
[Ctrl_test.txt](https://github.com/anfoss/PCprophet/files/7632137/Ctrl_test.txt)

2. About 2900 proteins.

3. Yes ann_cmplx.txt is empty.

Thanks

**Comment by anfoss** [comment] 2021-12-01 15:18
Ok so it is mouse data, in theory it should work so I would like to follow up via email. Can you send me the data?

**Comment by Maithy15** [comment] 2021-12-01 16:13
Yes, Could you please give me your ID?

**Comment by anfoss** [comment] 2021-12-01 16:16
Andrea.fossati@ucsf.edu

**Comment by anfoss** [comment] 2021-12-01 17:41
Can you attach the data here? Seems I did not receive your email

**Comment by Maithy15** [comment] 2021-12-01 18:36
Here you go! [Ctrl.txt](https://github.com/anfoss/PCprophet/files/7636403/Ctrl.txt)

**Comment by anfoss** [comment] 2021-12-01 21:23
Ok try copying the repo now and use the command line version, I just pushed a fix

**Closed by anfoss** 2021-12-01 21:23 UTC
